FROM metocean/ops-base

RUN yum -y update && \ 
    yum -y upgrade -y && \
    yum -y install \
    proj proj-devel tkinter libffi-dev libssl-dev libxml2-devel libxslt-devel zlib-devel \
	texlive texlive-* cython python-pyproj gfortran && \
    yum clean all

# Install proj from source
RUN cd /tmp &&\
    wget http://download.osgeo.org/proj/proj-4.9.2.tar.gz &&\
    tar -xvf proj-4.9.2.tar.gz  &&\
    cd proj-4.9.2 &&\
    ./configure &&\
    make install &&\
    cd &&\
    rm -fr /tmp/proj-4.9.2 /tmp/proj-4.9.2.tar.gz

RUN mkdir /www/ && git clone https://github.com/rtfd/readthedocs.org.git /www
WORKDIR /www

RUN pip install -r requirements.txt

RUN ./manage.py migrate && \
    echo "from django.contrib.auth.models import User; \
    User.objects.create_superuser('admin', 'admin@localhost', 'admin')" | \
    ./manage.py shell && \
    echo "yes" | ./manage.py collectstatic && \
    ./manage.py loaddata test_data

# Fix a bug in readthedocs
RUN pip install -U virtualenv

RUN echo "ALLOW_PRIVATE_REPOS=True" > \
    /www/readthedocs/settings/local_settings.py # private repo
RUN echo "ACCOUNT_EMAIL_VERIFICATION='none'" >> \
    /www/readthedocs/settings/local_settings.py # disable email verification

COPY .ssh /root/.ssh
RUN  chmod 700 /root/.ssh &&\
     chmod 600 /root/.ssh/id_rsa 

RUN yum -y install perl-Digest-MD5 perl-Tk

RUN rm -rf /usr/local/texlive/2016 &&\
	rm -rf ~/.texlive2016 

RUN mkdir /tmp/tex && cd /tmp/tex &&\
    wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz

RUN tar -xvf install-tl-unx.tar.gz &&\
    ./install-tl



CMD ["/www/manage.py", "runserver", "0.0.0.0:8000"]